# Project: DEV_C++ 5.11
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = .//RH_gui.o .//RH_gui_api.o .//RH_assert.o .//RH_data.o .//RH_dsp.o .//RH_dummy.o .//RH_graphic.o .//RH_image.o .//RH_lib.o .//RH_math.o .//RH_utility.o .//main.o .//RH_font.o .//RH_font_ArialRoundedBold.o .//RH_font_CourierNew.o .//RH_font_CourierNewBold.o
LINKOBJ  = .//RH_gui.o .//RH_gui_api.o .//RH_assert.o .//RH_data.o .//RH_dsp.o .//RH_dummy.o .//RH_graphic.o .//RH_image.o .//RH_lib.o .//RH_math.o .//RH_utility.o .//main.o .//RH_font.o .//RH_font_ArialRoundedBold.o .//RH_font_CourierNew.o .//RH_font_CourierNewBold.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"../BlackHouse" -I"../Glucoo" -I"../Glucoo/STB" -I"../Glucoo/Font"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"../BlackHouse" -I"../Glucoo" -I"../Glucoo/STB" -I"../Glucoo/Font"
BIN      = "DEV_C++ 5.11.exe"
CXXFLAGS = $(CXXINCS) -g3 -std=gnu99
CFLAGS   = $(INCS) -g3 -std=gnu99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

.//RH_gui.o: ../Glucoo/RH_gui.c
	$(CC) -c ../Glucoo/RH_gui.c -o .//RH_gui.o $(CFLAGS)

.//RH_gui_api.o: ../Glucoo/RH_gui_api.c
	$(CC) -c ../Glucoo/RH_gui_api.c -o .//RH_gui_api.o $(CFLAGS)

.//RH_assert.o: ../BlackHouse/RH_assert.c
	$(CC) -c ../BlackHouse/RH_assert.c -o .//RH_assert.o $(CFLAGS)

.//RH_data.o: ../BlackHouse/RH_data.c
	$(CC) -c ../BlackHouse/RH_data.c -o .//RH_data.o $(CFLAGS)

.//RH_dsp.o: ../BlackHouse/RH_dsp.c
	$(CC) -c ../BlackHouse/RH_dsp.c -o .//RH_dsp.o $(CFLAGS)

.//RH_dummy.o: ../BlackHouse/RH_dummy.c
	$(CC) -c ../BlackHouse/RH_dummy.c -o .//RH_dummy.o $(CFLAGS)

.//RH_graphic.o: ../BlackHouse/RH_graphic.c
	$(CC) -c ../BlackHouse/RH_graphic.c -o .//RH_graphic.o $(CFLAGS)

.//RH_image.o: ../BlackHouse/RH_image.c
	$(CC) -c ../BlackHouse/RH_image.c -o .//RH_image.o $(CFLAGS)

.//RH_lib.o: ../BlackHouse/RH_lib.c
	$(CC) -c ../BlackHouse/RH_lib.c -o .//RH_lib.o $(CFLAGS)

.//RH_math.o: ../BlackHouse/RH_math.c
	$(CC) -c ../BlackHouse/RH_math.c -o .//RH_math.o $(CFLAGS)

.//RH_utility.o: ../BlackHouse/RH_utility.c
	$(CC) -c ../BlackHouse/RH_utility.c -o .//RH_utility.o $(CFLAGS)

.//main.o: main.c
	$(CC) -c main.c -o .//main.o $(CFLAGS)

.//RH_font.o: ../Glucoo/Font/RH_font.c
	$(CC) -c ../Glucoo/Font/RH_font.c -o .//RH_font.o $(CFLAGS)

.//RH_font_ArialRoundedBold.o: ../Glucoo/Font/RH_font_ArialRoundedBold.c
	$(CC) -c ../Glucoo/Font/RH_font_ArialRoundedBold.c -o .//RH_font_ArialRoundedBold.o $(CFLAGS)

.//RH_font_CourierNew.o: ../Glucoo/Font/RH_font_CourierNew.c
	$(CC) -c ../Glucoo/Font/RH_font_CourierNew.c -o .//RH_font_CourierNew.o $(CFLAGS)

.//RH_font_CourierNewBold.o: ../Glucoo/Font/RH_font_CourierNewBold.c
	$(CC) -c ../Glucoo/Font/RH_font_CourierNewBold.c -o .//RH_font_CourierNewBold.o $(CFLAGS)
